language: go

go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - tip

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libgit2
install: make deps && make install
script: make test
