language: go

go:
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - tip

install:
    - go get -d github.com/libgit2/git2go
    - cd "${HOME}/gopath/src/github.com/libgit2/git2go"
    - git submodule update --init
    - make install
    - go get -u github.com/lib/pq
    - go get -u github.com/spaolacci/murmur3
script: make test
